### ISSUE TITLE
Reference for Cascade-SegNet?

### ISSUE THREAD

**Issue by pengpaiSH** [CSAILVision/sceneparsing#1]
As we all know, SegNet is available in public. However, Cascade-Segnet and Cascade-DilatedNet are both reported as state-of-the-art. Can some please explain what is the difference between SegNet and Cascade-SegNet?

**Comment by pengpaiSH** [comment]
@hangzhaomit

**Comment by metalbubble** [comment]
Thanks for your interest. Cascade is a new network design proposed in our paper, which will be released on arxiv soon.

**Comment by pengpaiSH** [comment]
@metalbubble Thank you for your clarifying. By the way, the released DilatedNet Caffe Model URL link is not available for downloading. Hope this will be fixed as soon as possible.

**Comment by hangzhaomit** [comment]
@pengpaiSH This was already solved, thanks.
