### ISSUE TITLE
Mirrored Data File Download?

### ISSUE THREAD

**Issue by sdeck51** [CSAILVision/sceneparsing#10]
Hi,

This isn't exactly related to the code, but I cannot download the train/val data from the website. I'm getting interruptions and corrupted zip files. Is there a mirror for the data?

Thanks

**Comment by metalbubble** [comment]
please redownload again to have a try. recently we migrated the data to another directory, probably you downloading is interrupted by this

**Comment by sdeck51** [comment]
Yeah I'm trying again and I can get to about 30MB and it "finishes".

**Comment by metalbubble** [comment]
We tested and didn't have any issues about downloading the file. Please check your network or ask your friends to download for you.
