### ISSUE TITLE
Licencing for ADE20K Dataset

### ISSUE THREAD

**Issue by jameswhennessey** [CSAILVision/sceneparsing#19]
Hello!
Great work and thanks for releasing the dataset! I was curious what the license is for the dataset?
Thanks!

**Comment by hangzhaomit** [comment]
Thanks for the reminder, I've added License.

**Comment by orlyliba** [comment]
Is there a license for the ADE20K dataset?
The license for this repository covers the code, but not the dataset, because the dataset is hosted in:https://groups.csail.mit.edu/vision/datasets/ADE20K/ and not in this repository.
Thank you

**Comment by orlyliba** [comment]
I now see that the data is also here: http://sceneparsing.csail.mit.edu/
and this website links to the license in this repository.
Does this mean that the dataset (images and annotations) are under the same license?
Thank you!

**Comment by TheKanter** [comment]
I'd like to echo @orlyliba questions. The BSD 3-clause license is great. However, I'd like to know what components it applies to. For example:

1. The images located at http://placeschallenge.csail.mit.edu/data/ChallengeData2017/images.tar
2. The release test located at http://placeschallenge.csail.mit.edu/data/ChallengeData2017/release_test.tar
3. The annotations located at http://placeschallenge.csail.mit.edu/data/ChallengeData2017/annotations_instance.tar

Are these all subject to the BSD 3-clause license (especially the images)?

@hangzhaomit @zhoubolei

**Comment by hangzhaomit** [comment]
Yes, all the images and annotations are all subject to the same license.

**Comment by TheKanter** [comment]
Thank you!

**Comment by Daniil-Osokin** [comment]
@hangzhaomit Hi! Thanks for the great dataset! Does the all data in the ["Download"](http://sceneparsing.csail.mit.edu/#Download) section have BSD 3-clause license? The links above cover only instance segmentation annotation.
