### ISSUE TITLE
ADE20k classes

### ISSUE THREAD

**Issue by AAnoosheh** [CSAILVision/sceneparsing#26]
So I have a question about the ADE20k itself.

I read all the seg-masks from the training set (~15k files) and counted the number of unique class values. I got 2231 unique values, where the highest value is 3144. This makes no sense as the number of classes is supposed to be 150.

I'm using this code to load the *_seg.png files in Python (adapted from the Matlab code on the dataset site):

```
mask = np.array(Image.open(mask_path), dtype=np.uint16)
R,G,B = mask[:,:,0], mask[:,:,1], mask[:,:,2]
class_mask = R // 10 * 256 + G
```

**Comment by thaoshibe** [comment]
Did you know how it work?
I created similar version of load_seg_ade20k (python) and used matching_index file
But the mapping is not 1-1
Some categories I cant found in the txt file!
