### ISSUE TITLE
How to create more training date with some extra classes

### ISSUE THREAD

**Issue by sauravbandral** [CSAILVision/sceneparsing#27]
Hi
I have been trying so create more training data with the object which are not accurately detected to improve the segmentation, but i can't figure out which color encoding to use which will give me single channel masking like yours. I have tried to pass same colored annotations with the encoding given in color150.mat file but the color encoding used in the original ADE20K dataset annotation are different. 
In the below below images the floor color encoding are different. The green floor one will give the single channel input as required but the brown floor one will give only black mask. So can anyone tell me how to get the correct color encoding to pass it from https://github.com/CSAILVision/sceneparsing/blob/master/convertFromADE/convertFromADE.m to get annotations

![6](https://user-images.githubusercontent.com/42890309/70689356-12147400-1cda-11ea-96bb-99d1c42cb8cc.png)
![ADE_train_00000196_seg](https://user-images.githubusercontent.com/42890309/70689446-4f790180-1cda-11ea-9438-b0c80b496b25.png)

**Comment by xavierpuigf** [comment]
The function `convertFromADE.m` expects masks from the original ADE20K dataset, like the one below. The image on the top is already in the sceneparsing challenge format. 
[Here](
https://github.com/CSAILVision/sceneparsing/blob/master/visualizationCode/color150.mat) is the mapping from colors in that format (top image), to the ids.

**Comment by sauravbandral** [comment]
Thank you @xavierpuigf  for getting back to me so fast.
But how would we get this color [mask](https://user-images.githubusercontent.com/42890309/70689446-4f790180-1cda-11ea-9438-b0c80b496b25.png) from the original [image ](https://user-images.githubusercontent.com/42890309/70773287-0938a680-1d9d-11ea-97bf-ab1f32cd3bfe.jpg) which we can pass through convertFromADE.m to get this [annotation](https://user-images.githubusercontent.com/42890309/70773405-67658980-1d9d-11ea-913a-f8213dc618f4.png)

**Comment by sauravbandral** [comment]
I have figured it out, thanks anyway
