### ISSUE TITLE
Which method does the online demo use? FCN, SegNet, Dialated ... ?

### ISSUE THREAD

**Issue by pengpaiSH** [CSAILVision/sceneparsing#3]
I have tried several images with the online segmentation [demo](http://scenesegmentation.csail.mit.edu/) and surprisingly it works quite well! I would like to ask which method does this use, FCN, SegNet, DialtedNet, or ensembles with XXX ?

**Comment by pengpaiSH** [comment]
@metalbubble @hangzhaomit

**Comment by hangzhaomit** [comment]
@pengpaiSH The online demo uses DilatedNet, thanks for the comment!

**Comment by pengpaiSH** [comment]
@hangzhaomit Thank you for your attention and feedback~
