### ISSUE TITLE
Can't reproduce test results using pre-trained Dilated model

### ISSUE THREAD

**Issue by ieted** [CSAILVision/sceneparsing#4]
Using the offered DilatedNet_iter_120000.caffemodel model and demoSegmentation.m script, I am unable to reproduce the qualitative test results posted at the bottom of README file (see here https://github.com/CSAILVision/sceneparsing#pre-trained-models-on-going). [Here](https://drive.google.com/open?id=0B_HmvzQMuOj1NzdYdDBIbTZkT2s) are two examples I got using DilatedNet caffe model. 

Are the released models exactly the same with the ones you are using?

**Comment by pengpaiSH** [comment]
+1 I also found this problem! @hangzhaomit

**Comment by xavierpuigf** [comment]
There was an error in the demoSegmentation.m script. You should now be able to reproduce the segmentation results correctly.

Thanks for noticing

**Comment by pengpaiSH** [comment]
@xavierpuigf  Thanks for your quick response. Would you mind having a look at the other issue that I asked?
