### ISSUE TITLE
Location of caffemodels

### ISSUE THREAD

**Issue by Achilles-96** [CSAILVision/sceneparsing#6]
Can you please tell where can I get the required caffemodels?

**Comment by hangzhaomit** [comment]
@Achilles-96 Please check the links in the demo scripts.

**Comment by Achilles-96** [comment]
Oh, missed that!! Thanks :)
Just for anyone's reference -
http://sceneparsing.csail.mit.edu/model/FCN_iter_160000.caffemodel
http://sceneparsing.csail.mit.edu/model/DilatedNet_iter_120000.caffemodel
